import {
  facebook,
  linkedin,
  instagram,
  twitter,
  github,
  facebook1,
  linkedin1,
  instagram1,
  twitter1,
  github1,
  tvshowbox,
  guesstheword,
  xing,
  xing1,
  tictactoe,
  mathmagician,
  metricwebapp,
  spacetravelers,
  recipeapp,
  trackbudget,
  carrental,
  eva,
  ados,
  runn,
  locks,
  priojon,
  letsusedata,
  guesstheword1,
  guesstheword2,
  guesstheword3,
  spacetravelers1,
  spacetravelers2,
  spacetravelers3,
  tictactoe1,
  tictactoe2,
  tictactoe3,
  tvshow1,
  tvshow2,
  tvshow3,
  metricswebapp1,
  metricswebapp2,
  recipeapp3,
  recipeapp4,
  recipeapp6,
  trackbuget1,
  trackbuget2,
  trackbuget5,
  carrental3,
  carrental4,
  carrental6,
  eva1,
  eva2,
  eva3,
  ados1,
  ados2,
  ados3,
  runn1,
  runn2,
  runn3,
  locks1,
  locks2,
  locks3,
  priojon1,
  priojon2,
  priojon3,
  letsusedata1,
  letsusedata2,
  letsusedata3,
  responsive,
  react,
  fullstack,
} from "../assets";

const social = [
  {
    id: 1,
    name: "LinkedIn",
    url: "https://www.linkedin.com/in/ernesto-munes-815895273/",
    icon: linkedin,
    icon1: linkedin1,
  },
  {
    id: 2,
    name: "Github",
    url: "https://github.com/0xalpha0123",
    icon: github,
    icon1: github1,
  },
  {
    id: 3,
    name: "Xing",
    url: "https://www.xing.com/profile/Ernesto_Munes/cv",
    icon: xing,
    icon1: xing1,
  },
];

const technologies = [
  {
    stack: ["languages", "all"],
    name: "HTML 5",
    icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/html5/html5-plain.svg",
  },
  {
    stack: ["languages", "all"],
    name: "CSS 3",
    icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/css3/css3-plain.svg",
  },
  {
    stack: ["languages", "all"],
    name: "C#",
    icon: "https://static-00.iconduck.com/assets.00/c-sharp-c-icon-456x512-9sej0lrz.png",
  },
  {
    stack: ["languages", "all"],
    name: "JavaScript",
    icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/javascript/javascript-plain.svg",
  },
  {
    stack: ["tools", "all"],
    name: "Drupal",
    icon: "https://cdn-icons-png.flaticon.com/512/889/889096.png",
  },
  {
    stack: ["tools", "all"],
    name: "Wordpress",
    icon: "https://cdn-icons-png.flaticon.com/512/174/174881.png",
  },
  {
    stack: ["languages", "all"],
    name: "TypeScript",
    icon: "https://static-00.iconduck.com/assets.00/typescript-icon-icon-512x512-yh0yu3ta.png",
  },
  {
    stack: ["languages", "all"],
    name: "PHP",
    icon: "https://static-00.iconduck.com/assets.00/php-icon-512x512-og0oh3rg.png",
  },
  {
    stack: ["frameworks", "all"],
    name: ".Net",
    icon: "https://static-00.iconduck.com/assets.00/dotnet-icon-512x489-aorslxyh.png",
  },
  {
    stack: ["frameworks", "all"],
    name: "Asp.Net",
    icon: "https://static-00.iconduck.com/assets.00/programming-language-aspnet-icon-512x339-fqrnblwn.png",
  },
  {
    stack: ["frameworks", "all"],
    name: "ReactJS",
    icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/react/react-original.svg",
  },
  {
    stack: ["frameworks", "all"],
    name: "VueJS",
    icon: "https://static-00.iconduck.com/assets.00/vue-icon-512x442-q8uxz5az.png",
  },
  {
    stack: ["frameworks", "all"],
    name: "NextJS",
    icon: "https://static-00.iconduck.com/assets.00/nextjs-icon-512x309-yynfidez.png",
  },
  {
    stack: ["frameworks", "all"],
    name: "Laravel",
    icon: "https://static-00.iconduck.com/assets.00/laravel-icon-497x512-uwybstke.png",
  },
  {
    stack: ["frameworks", "all"],
    name: "NodeJS",
    icon: "https://static-00.iconduck.com/assets.00/node-js-icon-512x314-xwmxlccc.png",
  },
  {
    stack: ["frameworks", "all"],
    name: "Bootstrap",
    icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/bootstrap/bootstrap-plain.svg",
  },
  {
    stack: ["frameworks", "all"],
    name: "Tailwind CSS",
    icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/tailwindcss/tailwindcss-plain.svg",
  },
  {
    stack: ["frameworks", "all"],
    name: "Material UI",
    icon: "https://static-00.iconduck.com/assets.00/material-ui-icon-512x406-fhnu85xg.png",
  },
  {
    stack: ["tools", "all"],
    name: "Figma",
    icon: "https://www.vectorlogo.zone/logos/figma/figma-icon.svg",
  },
  {
    stack: ["tools", "all"],
    name: "Adobe XD",
    icon: "https://static-00.iconduck.com/assets.00/adobe-xd-icon-512x512-w8f2hoan.png",
  },
];

const projects = [
  {
    id: 1,
    name: "ADOS - WordPress Custom Theme",
    desc: "To create a custom website design & develop in WordPress for ADOS.",
    tech: [
      "WordPress",
      "PHP",
      "AJAX",
      "CMS",
      "HTML5",
      "CSS",
      "Bootstrap",
      "jQuery",
    ],
    img: ados,
    carousel: [ados1, ados2, ados3],
    source_link: "#",
    live_link: "https://ados.pro/",
  },
  {
    id: 2,
    name: "Watchdog WooCommerce Custom Theme",
    desc: "To develop custom WooCommerce website to add products for sale and ensure that customers can purchase the products by placing them in a shopping cart and making a payment online with special services.",
    tech: [
      "WordPress",
      "PHP",
      "AJAX",
      "CMS",
      "HTML5",
      "CSS",
      "Bootstrap",
      "jQuery",
    ],
    img: locks,
    carousel: [locks1, locks2, locks3],
    source_link: "https://github.com/0xalpha0123/EVA",
    live_link: "https://www.wdlocks.co.uk",
  },
  {
    id: 3,
    name: "Runn Custom WordPress Theme",
    desc: "To design and develop custom WordPress website for RUNIN.",
    tech: [
      "WordPress",
      "PHP",
      "AJAX",
      "CMS",
      "HTML5",
      "CSS",
      "Bootstrap",
      "jQuery",
    ],
    img: runn,
    carousel: [runn1, runn2, runn3],
    source_link: "https://github.com/0xalpha0123/EVA",
    live_link: "https://runinproject.eu",
  },
  {
    id: 4,
    name: "EVirtualAssistants",
    desc: "The EVirtualAssistants is a full-stack platform we built using React as Front-end and Asp.Net as the Back-end API with custom authentication. The companies can find virtual assistants with budget in the Philippine.",
    tech: ["React", "Redux", "Asp.Net", "Microsoft SQL Service"],
    img: eva,
    carousel: [eva1, eva2, eva3],
    source_link: "https://github.com/0xalpha0123/EVA",
    live_link: "https://evirtualassistants.com/",
  },
  {
    id: 5,
    name: "Priojon",
    desc: "The Priojon app keeps track of all registers(male and female). It allows you to connect, message, chat and meet your partner from all over the world. We have many couples who had benefit from our platform",
    tech: ["React", "Redux Toolkit", "NodeJS", "MongoDB"],
    img: priojon,
    carousel: [priojon1, priojon2, priojon3],
    source_link: "https://github.com/0xalpha0123/Priojon-Server",
    live_link: "https://priojon.com/",
  },
  {
    id: 6,
    name: "LetsUseData",
    desc: "The LetsUseData app is a platform that serves online education courses and tests. It has many features including video support service, self-test modules and several online courses. Due to Covid-19, many students and parents give their interests to this platform in US.",
    tech: ["React", "Redux Toolkit", "Asp.Net core", "Microsoft Azure SQL"],
    img: letsusedata,
    carousel: [letsusedata1, letsusedata2, letsusedata3],
    source_link: "https://github.com/0xalpha0123/letsusedata",
    live_link: "https://letsusedata.com/",
  },
  {
    id: 7,
    name: "TV Shows Box",
    desc: "TVshows Box is a web application showing multiple TV shows with the help of TVmaze API which contains both mobile and desktop versions. The webapp have 3 interfaces: - A home page, a popup window, and a contact page.",
    tech: ["HTML5", "CSS3", "JavaScript", "TVmaze API"],
    img: tvshowbox,
    carousel: [tvshow1, tvshow2, tvshow3],
    source_link: "https://github.com/Rhaegar121/TVshows_Box",
    live_link: "https://tvshowbox.netlify.app/",
  },
  {
    id: 8,
    name: "Guess the word",
    desc: "Guess The Word is a fun letter puzzle game where the player have to guess the hidden word using the clues that the game gives. The game ends if the player guesses the correct word or if he chooses the wrong letter 8 times. Mainly built with Javascript.",
    tech: ["HTML5", "CSS3", "JavaScript"],
    img: guesstheword,
    carousel: [guesstheword1, guesstheword2, guesstheword3],
    source_link: "https://github.com/Rhaegar121/Guess-the-word",
    live_link: "https://guess-the-word121.netlify.app/",
  },
  {
    id: 9,
    name: "Car Rental App",
    desc: "The Car Rental App is a full-stack app we built using React as Front-end and Ruby on Rails as the Back-end API with custom authentication. The users can see a list of cars to rent and add to their favorites. The users can also add a car to the list and delete a car from the list.",
    tech: ["React", "Redux", "Ruby on Rails", "PostgreSQL"],
    img: carrental,
    carousel: [carrental3, carrental4, carrental6],
    source_link: "https://github.com/Rhaegar121/Car-Rental-front-end",
    live_link: "https://car-rental-capstone.netlify.app/",
  },
  {
    id: 10,
    name: "Recipe App",
    desc: "The Recipe app keeps track of all your foods, recipes, and ingredients. It allows you to save ingredients, keep track of what you have, create recipes, and generate a shopping list based on what you have and what you are missing from a recipe. Since sharing recipes is an important part, it allows you to make them public so anyone can access them.",
    tech: ["Ruby", "Ruby on Rails", "PostgreSQL"],
    img: recipeapp,
    carousel: [recipeapp3, recipeapp4, recipeapp6],
    source_link: "https://github.com/Rhaegar121/Recipe-App",
    live_link: "https://recipe-app121-b8888e20687b.herokuapp.com/",
  },
  {
    id: 11,
    name: "Track Budget App",
    desc: "Track Budget is a mobile web application where you can manage your budget: you have a list of purchases associated with a category, so that you can see how much money you spent and on what category.",
    tech: ["Ruby", "Ruby on Rails", "PostgreSQL"],
    img: trackbudget,
    carousel: [trackbuget1, trackbuget2, trackbuget5],
    source_link: "https://github.com/Rhaegar121/Track-Budget",
    live_link: "https://track-budget121-70a570d4e3e1.herokuapp.com/",
  },
  {
    id: 12,
    name: "Space Travelers' Hub",
    desc: "Space Travelers' Hub is a web application that provides commercial and scientific space travel services using the real live data from the SpaceX API. The application will allow users to book rockets and join selected space missions.",
    tech: ["React", "Redux", "SpaceX API"],
    img: spacetravelers,
    carousel: [spacetravelers1, spacetravelers2, spacetravelers3],
    source_link: "https://github.com/Rhaegar121/React-Group-Project",
    live_link: "https://space-travelers-hub121.netlify.app/",
  },
];

const testimonials = [
  {
    id: 1,
    name: "Ben Tessier",
    image: "https://ca.slack-edge.com/T74B16CPP-U753N092A-4227e585ca3f-512",
    text: "Choosing Ronny as our full stack developer was one of the best decisions we made. Their expertise in PHP and Drupal proved instrumental in developing a robust and user-friendly web application.",
    country: "Canada",
    linkedIn: "https://www.linkedin.com/in/ben-tessier-3a2115250/",
  },
  {
    id: 2,
    name: "Ayaz Ur Rehman",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTGEo3_UrM7O2AS5Ei6SJG0IL9-NxCwDHCj74bXLeIQlA&s",
    text: "We hired Ronny as our full stack developer for an important web application development project. His expertise in WordPress and Drupal, coupled with their excellent communication skills, made the entire process effortless.",
    country: "United Arab Emirates",
    linkedIn: "https://www.linkedin.com/in/elenakovacs/",
  },
  {
    id: 3,
    name: "Elena Kovács ",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTGEo3_UrM7O2AS5Ei6SJG0IL9-NxCwDHCj74bXLeIQlA&s",
    text: "Working with him was an absolute pleasure. He was always responsive to our needs, quick to address any issues, and consistently exceeded our expectations. We highly recommend him for any full stack development project.",
    country: "Germany",
    linkedIn: "https://www.linkedin.com/in/muhammad-talha-hanif/",
  },
  {
    id: 4,
    name: "Pasquale Silvio Pisu",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTGEo3_UrM7O2AS5Ei6SJG0IL9-NxCwDHCj74bXLeIQlA&s",
    text: "I really am comfortable with collaborating and coding with Ronny. His ingenious ideas give me a lot of ideas solving a problem multiple ways.",
    country: "Italy",
    linkedIn: "",
  },
];

const services = [
  {
    id: 1,
    icon: react,
    title: "Front-end Development",
    text: "Crafting captivating interfaces with cutting-edge technologies to ensure dynamic and user-friendly web experiences.",
  },
  {
    id: 2,
    icon: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/rails/rails-plain.svg",
    title: "Back-end Development",
    text: "Building the engine behind your applications, enabling robust functionality, and efficient data management.",
  },
  {
    id: 3,
    icon: fullstack,
    title: "Full-stack Development",
    text: "From pixel to database, I create holistic solutions that harmonize frontend finesse with backend power.",
  },
  {
    id: 4,
    icon: responsive,
    title: "Database Optimization",
    text: "Carefully organizing data, designing best structure, creating efficient indexes, and refining SQL queries.",
  },
];

const navLinks = [
  {
    id: 1,
    name: "About",
    url: "/#about",
  },
  {
    id: 2,
    name: "Service",
    url: "/#service",
  },
  {
    id: 3,
    name: "Work",
    url: "/#work",
  },
  {
    id: 4,
    name: "Testimonial",
    url: "/#testimonial",
  },
  {
    id: 5,
    name: "Contact",
    url: "/#contact",
  },
];

export { technologies, projects, testimonials, social, services, navLinks };
